media:
  input: public/work
  output: /work

content:
  - name: blog
    label: Council Blog
    type: collection
    path: src/content/blog
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Short Summary
        type: string
      - name: date
        label: Publish Date
        type: date
      - name: draft
        label: Is this a draft?
        type: boolean
        default: false
      - name: body
        label: Post Content
        type: rich-text